# Generated by Django 2.0.5 on 2018-05-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('shop_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(default='', max_length=200)),
                ('review_count', models.CharField(default='', max_length=20)),
                ('avg_price', models.CharField(default='', max_length=20)),
                ('taste', models.CharField(default='', max_length=10)),
                ('env', models.CharField(default='', max_length=10)),
                ('service', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=200)),
                ('open_time', models.CharField(default='', max_length=200)),
                ('rank_star', models.CharField(default='', max_length=20)),
                ('place', models.CharField(default='', max_length=20)),
                ('classify', models.CharField(default='', max_length=20)),
                ('star_all', models.CharField(default='', max_length=20)),
                ('star_5', models.CharField(default='', max_length=20)),
                ('star_4', models.CharField(default='', max_length=20)),
                ('star_3', models.CharField(default='', max_length=20)),
                ('star_2', models.CharField(default='', max_length=20)),
                ('star_1', models.CharField(default='', max_length=20)),
                ('feature', models.BooleanField(default=False)),
                ('feature2', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
