# Generated by Django 2.0.5 on 2018-05-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDedail',
            fields=[
                ('shop_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('star_all', models.CharField(max_length=20, null=True)),
                ('star_5', models.CharField(max_length=20, null=True)),
                ('star_4', models.CharField(max_length=20, null=True)),
                ('star_3', models.CharField(max_length=20, null=True)),
                ('star_2', models.CharField(max_length=20, null=True)),
                ('star_1', models.CharField(max_length=20, null=True)),
                ('first_review_time', models.CharField(max_length=100, null=True)),
                ('first_review_content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopId',
            fields=[
                ('shop_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('from_url', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
