# Generated by Django 2.0.5 on 2018-05-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_reviewdedail_shopid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
